

ROOT = ../../..

TARGET = $(ROOT)/bin/stutter
OBJS =	simple.o \
	input.o \
	window.o \
	statusbar.o \
	terminal.o \
	net.o \
	$(MODULES) \
	$(ROOT)/src/main.a

LIBS = -lncurses

include $(ROOT)/rules.mk



