

ROOT = ../../..

LIB_TARGET = simple.a
OBJS =	simple.o \
	input.o \
	window.o \
	statusbar.o \
	screen.o \
	net.o \

ARFLAGS = rc
CFLAGS = -g -I$(ROOT)/include -DNET_DIRECT

include $(ROOT)/rules.mk



