

ROOT = ../../..

LIB_TARGET = modbase.a
OBJS =	init.o \
	cmds/alias.o \
	cmds/bind.o \
	cmds/clear.o \
	cmds/clearline.o \
	cmds/echo.o \
	cmds/evaluate.o \
	cmds/exec.o \
	cmds/get.o \
	cmds/next.o \
	cmds/parse.o \
	cmds/previous.o \
	cmds/quit.o \
	cmds/redirect.o \
	cmds/remove.o \
	cmds/scroll.o \
	cmds/set.o \
	cmds/source.o \
	cmds/unbind.o \
	sigs/print.o \
	types/command.o \
	types/format.o \
	types/status.o \
	types/string.o \
	types/table.o \
	types/time.o \
	types/wildcard.o

include $(ROOT)/rules.mk

