

ROOT = ../../..

LIB_TARGET = modbase.a
OBJS =	cmds/next.o \
	cmds/previous.o \
	cmds/scroll.o \
	cmds/get.o \
	cmds/set.o \
	cmds/parse.o \
	cmds/remove.o \
	types/command.o

ARFLAGS = rc
CFLAGS = -g -I$(ROOT)/include

include $(ROOT)/builder/builder.mk

