

ROOT = ../../..

LIB_TARGET = fecommon.a
OBJS =	cmds/insert.o \
	core/colourmap.o \
	core/layout.o \
	core/widget.o \
	types/attrib.o \
	types/colour.o \
	types/command.o \
	types/style.o \
	utils/format.o \
	widgets/container.o \
	widgets/frame.o \
	widgets/input.o \
	widgets/region.o \
	widgets/statusbar.o \
	widgets/text.o \
	widgets/window.o

include $(ROOT)/rules.mk


