

ROOT = ../../..

LIB_TARGET = fecommon.a
OBJS =	init.o \
	cmds/echo.o \
	cmds/insert.o \
	cmds/next.o \
	cmds/parse.o \
	cmds/previous.o \
	core/colourmap.o \
	core/key.o \
	core/layout.o \
	core/surface.o \
	core/widget.o \
	utils/format.o \
	widgets/container.o \
	widgets/frame.o \
	widgets/input.o \
	widgets/page.o \
	widgets/region.o \
	widgets/statusbar.o \
	widgets/text.o \
	widgets/window.o

# TODO finish coverting these
#	types/attrib.o \
#	types/colour.o \
#	types/command.o \
#	types/hashattrib.o \
#	types/style.o \

include $(ROOT)/rules.mk


