

ROOT = ../../..

LIB_TARGET = fecommon.a
OBJS =	cmds/bind.o \
	cmds/clear.o \
	cmds/clearline.o \
	cmds/close.o \
	cmds/context.o \
	cmds/echo.o \
	cmds/insert.o \
	cmds/next.o \
	cmds/parse.o \
	cmds/previous.o \
	cmds/scroll.o \
	cmds/select.o \
	cmds/unbind.o \
	cmds/window.o \
	core/colourmap.o \
	core/key.o \
	core/surface.o \
	core/widget.o \
	sigs/create.o \
	sigs/destroy.o \
	sigs/print.o \
	utils/format.o \
	widgets/container.o \
	widgets/frame.o \
	widgets/input.o \
	widgets/page.o \
	widgets/statusbar.o \
	widgets/text.o \
	widgets/window.o

#	widgets/region.o \
#	types/attrib.o \
#	types/colour.o \
#	types/hashattrib.o \
#	types/style.o \

include $(ROOT)/rules.mk


