

ROOT = ..

LIB_TARGET = main.a
OBJS =	main.o \
	key.o \
	type.o \
	utils.o \
	signal.o \
	variable.o \
	lib/memory.o \
	lib/string.o

ARFLAGS = rc
CFLAGS = -g -I$(ROOT)/include

include $(ROOT)/rules.mk



